### ISSUE TITLE
Configurable dendrogram panel

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#100]
# User Story

Users of Mastodon would like to toggle on/off the classification threshold and the median line shown in the dendrogram. Furthermore, it would be nice to manipulate the labeling of the leaves shown in the dendrogram, i.e. toggle on/off root names, toggle on/off associated tag labels and also to select the tagset to be used.

# Tasks:
- [x] Provide Checkboxes to toggle on/off
  - [x] Threshold line
  - [x] Median line
  - [x] Root names
  - [x] Tag labels
- [x] Select box to choose tagset
- [x] Make DendrogramView to react when tagsets are changed
- [x] Reflect choices in the export
- [x] Persist choices, if possible
