### ISSUE TITLE
Lineage Classification Averaging Multiple Embryos

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#101]
# User Story

I would like to be able to process the lineage classification averaging over multiple embryos of the same species.
With this I would like to reproduced the steps describe in [Guignard et al. 2020, p. 46](https://www.science.org/doi/suppl/10.1126/science.aar5663/suppl_file/aar5663_guignard_sm.pdf)

![grafik](https://github.com/mastodon-sc/mastodon-deep-lineage/assets/10515534/3fd81255-715f-4fd3-a2ff-a6b1c5c04829)

![grafik](https://github.com/mastodon-sc/mastodon-deep-lineage/assets/10515534/5f13f0a5-215a-470e-b7f6-63c3311a81df)

# Acceptance criteria

1. Possibility for the user to select multiple Mastodon projects to be included in the analysis
2. Filter commonly named root cells across all selected projects
3. Crop all projects at the same given number of cells (start and end)
4. Compute Distance matrix for all projects
5. Compute an averaged distance matrix
6. Use the averaged distance matrix to compute an average dendromgram/classification
7. Save the resulting tag set in all projects included in the classification.

# Tasks

* [x] Possibility for the user to select multiple Mastodon projects to be included in the analysis
  * [x] ~Put Similarity measure, Linking method and feature into advanced options~
  * [x] ~Alternatively provide a dialog with only a view options and an advanced dialog with all params~
  * [x] Use Array of files as Sci Java Command param
  * [x] Clear button for list of projects to be included
* [x] Filter commonly named root cells across all selected projects
* [x] Crop all projects at the same given number of cells (start and end)
* [x] Compute Distance matrix for all projects
* [x] Compute an averaged distance matrix
* [x] Use the averaged distance matrix to compute an average dendrogram/classification
* [x] Handle edge cases / provide user feedback
* [x] (Optionally) Save the resulting tag set in all projects included in the classification.
  * [x] Name the tag set as "Average ...
* [x] Related PR: https://github.com/scijava/scijava-ui-swing/pull/82
* [x] Related PR: https://github.com/mastodon-sc/mastodon/pull/311
* [x] Related PR: https://github.com/scijava/scijava-common/pull/479
* [x] Mention name of project from which the plugin was loaded before the list of further projects
* [x] Avoid loading the current open project in the list of further projects 
* [x] Avoid that projects are loaded twice in the list of further projects

Optional

* normalize time across embryos
  * select one representative and normalize the time to this (embryo pm08 in the case of guignard et al. 2020)
  * normalize time using local cost function normalization (corrected guignard distance)

* evaluation of classification quality:
  * use concept of entropy to measure if the quality of the automatic classification in comparison to the classification done manually by Mette
  * https://towardsdatascience.com/statistical-tests-for-comparing-classification-algorithms-ac1804e79bb7
