### ISSUE TITLE
Create TagSet from root nodes based on tree similarity

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#25]
# Story

Users would like to be able classify lineage trees depending on how similar they are to each other. Lineage trees that fall in the same class should get the same color (tag).

# Acceptance criteria

1. Users can choose a start timepoint or a start number of cells
2. Users can choose an end timepoint or an end number of cells
3. Users can choose the number of classes to be generated
4. Users can choose the similarity metrics. The default option is normalized zhang tree edit distance based on lifespan as weight.
5. A tagset is created based on theses settings. The tagset computation is based on a similarity matrix of all lineage trees in the data set and a hierarchical clustering (wards method) derived from it.

# Tasks
- [x] UI dialog for parameter selection
- [x] Find all roots starting from the selected start timepoint
- [x] Find all roots starting from the selected start number of cells
- [x] Compute the similarity matrix
- [x] Derive hierarchical clustering from the similarity matrix (average linkage)
- [x] Derive the selected number of classes from the similarity matrix
- [x] Create tagset from the computed classes. Assign a tag to each spot between start end endtimepoint
- [x] Explanations in dialog

# Related:

#24 

# Example Image 

This shows tagsets visualising the same cell fate. The visualisation of the same class could be similar:

![grafik](https://github.com/mastodon-sc/mastodon-deep-lineage/assets/10515534/e588fa5f-df6f-4c00-9b1a-b2acc7e3e22b)
