### ISSUE TITLE
Use Cluster Plotter for explorative data analysis

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#34]
# User Story

From a biological perspective, it would be interesting to perform an explorative study of a developmental biological dataset. The goal is to find out, which features that can already be computed (cf. #10, #11, #12, #13 and will possible to be computed in the future cf. #1, #6 / https://github.com/mastodon-sc/mastodon-pasteur/pull/9, #7, #9, ) are distinctive to separate different types of cells.

The underlying research question would be to find a out if there is a clustering method to reveal biologically relevant clusters (e.g. cell types).

# Tasks

* [x] **Load data of Averof Lab into Mastodon**
* [x] ~Perform ellipsoid fitting~
* [x] Compute all currently possible features
* [x] Export data as CSV 
  * [x] Spots
  * [x] ~(Links)~
  * [x] **BranchSpots**
  * [x] ~(BranchLinks)~
  * [x] Add Links between Spots and BranchSpots (#37)
* [x] Plugin to export ellipsoids as Label Image (#40)
* [x] Load data into Cluster Plotter
  * [x] Explore Spot features (Plot different features against each other)
  * [x] Explore BranchSpot features (Plot multiple features against each other)
  * [x] Check, if further features can be added using Napari region props
  * [x] Perform u-MAP / dimensionality reduction
    * [x] Try different subsets of features
    * [x] Run on Workstation if performance on local machine is too low
  * [x] Load image data / timelapse into Napari as well to understand potential clusters that can be seen in clusters plotter
    * [x] Test, if HDF5 image data can be imported
    * [x] Perhaps, convert HDF5 image data to TIFF data, if importing is easier then
  * [x] Make screenshots with potentially relevant settings for discussion in next meeting
* [x] **Perform tests with data by Mette**
* [x] Export data as CSV 
  * [x] Spots
  * [x] ~Links~
  * [x] BranchSpots
  * [x] ~BranchLinks~
* [x] Load data into Cluster Plotter
  * [x] Explore Spot features (Plot different features against each other)
  * [x] Explore BranchSpot features (Plot multiple features against each other)
  * [x] Try to find features + clustering settings that correspond to the labels (i.e. cell types) given by Mette

# Additional Information

##  Publicly available data by Averof lab ##

> You can find the zenodo link to the image dataset (+tracks) on this page: https://www.averof-lab.org/pages/2923-resources 

## Features of interest / features that are assumed to be biologically relevant ##
  * https://docs.google.com/document/d/107yOWeroBS3xZWMTV1Ieuv8u0m1KO-eA3JgH7qhA5_s/edit
  * https://docs.google.com/document/d/14U5RnJ59U9dsKmJWv3UL-_2rB9-T7XXnyZWsEf2YN_A/edit (page 3)

## Code for reading data exported from Mastodon into Napari Cluster plotter ##
  * https://gitlab.mn.tu-dresden.de/bia-pol/load_tracking_features_into_napari_clusters_plotter

**Comment by stefanhahmann** [comment]
U-MAP is implemented in a non-parallel way in Napari (making relatively long to process in a single thread):

![grafik](https://github.com/mastodon-sc/mastodon-deep-lineage/assets/10515534/a084cab6-5cf6-4fed-bb91-a3bfb1bb621f)
