### ISSUE TITLE
Export Label Image Using Spot Ellipsoids

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#40]
# Story

To be able to connect the image with the clusters plotter in Napari for #34 it would be good to have a label image of the same dataset available.
For this purpose, it would be good, if the use could select a property (e.g. BranchSpot ID, SpotID) that may be used as label value. The ellipsoids as segmentation source.

# Acceptance criteria:
* UI callable via Plugins
* Dialog to select the feature to be used as label
* Selection of Spot-Id, BranchSpot Id or Track Id
* Values set as selected inside the ellipsoids using all timepoints
* Result shown in BDV window
* Result is exportable

# TODO
* [x] Create Plugin
* [x] Create Menu Entry
* [x] Create Dialog
* [x] Selection Spot Id / BranchSpot Id / Track Id
* [x] Assign values inside ellipsoid
* [x] Show result
* [x] Possibility to save result
