### ISSUE TITLE
Export the similarity matrix of lineage tree classification as CSV

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#43]
# User Story

I would like to use the similarity matrix produced in the progress of #25 outside of Mastodon to do some data science.

# Acceptance criteria

* UI element for this action exists
* Similarity Matrix is exported as CSV
* Rows and Columns of CSV file start with root names

# TODOs
- [ ] Write similarity matrix as CSV
- [ ] Add UI element
- [ ] Add unit test
