### ISSUE TITLE
Reuse color of tagsets in dendrogram view

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#49]
# User Story

When using the function "Classification of Lineage" trees tagsets with different colors are generated. It would be nice, if these colors could also be used in the dendrogram view, 

# Acceptance Criteria

* The dendrogram is colored using the same colors that are use for the generated tagsets

# Tasks
- [x] Implement Mastodon DendrogramPanel, since currently used DendrogramPanel cannot be extended to do this
- [x] Re-Use colors for TagSets and for Clusters in the DendrogramPanel
- [x] Add Unit tests
