### ISSUE TITLE
Performance of Zhang Tree Edit Distance

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#59]
The computation of the Zhang Edit Distance of the trees 2aba and 1bab between timepoints 30 and 350 takes:
* with the BranchSpotTree implementation ~60.000ms
* with the SimpleTree implementation ~25.000ms
both is too long.
The purpose of this ticket is to improve this performance.

Mastodon file containing the two trees (amongst other):
- [flatSim2_be_2.zip](https://github.com/mastodon-sc/mastodon-deep-lineage/files/13476162/flatSim2_be_2.zip)

- The SimpleTree implementation is contained in this code example:
https://github.com/mastodon-sc/mastodon-deep-lineage/blob/master/src/test/java/org/mastodon/mamut/treesimilarity/tree/DenseSimpleTreeExamples.java

# Tasks
 - [x] Add the optimization for building the flow network in case of binary trees
 - [x] Do further profiling
 - [x] Add further optimization if possible
 - [x] Find reason, why BranchSpotTree so much slower than SimpleTree implementation

**Comment by stefanhahmann** [comment]
Many of the trees used with the tree edit distance implementation inside Mastodon are binary trees. For these trees the max flow min cost algorithm can be simplified.

![20240417_221326](https://github.com/mastodon-sc/mastodon-deep-lineage/assets/10515534/bbaf1cf9-e52b-4db7-b9f9-bf4574267516)
