### ISSUE TITLE
Average distance to n nearest neighbours

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#6]
# User Story

The average distance of a cell nuclei to its n nearest neighbours may be a possible descriptor of its fate already in early developmental stages. Thus, it would be good, if there was a feature computer that can compute the average distance to a configurable number of its closest neighbours.

# Acceptance criteria

1. Implemented as Spot Feature
1. Number of neighbours is configurable
1. Result is stored per spot in the feature table

# Tasks

- [ ] Create a Spot Feature "Average Distance"
- [ ] Allow UI input for the number of nearest neighbours to be considered
- [ ] Provide a method to select the n nearest neighbours of a cell nuclei
- [ ] Compute the the average distance to the specified number of near cell nucleis (Use KD-Tree im ImgLib)
- [ ] Store computed values in the feature table

# Additional Info:

- Example for spatial-temporal index in Mastodon: https://github.com/mastodon-sc/mastodon-tomancak/blob/c6d13d1f4e87096141157121f387786f74a9a8e4/src/main/java/org/mastodon/mamut/tomancak/util/SpotsIterator.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L148

**Comment by tinevez** [comment]
Hello @stefanhahmann 

Son in the team needs something that can compute statistics for the N nearest cells, whatever the stats is. I plan on making a plugin with a small UI that ask for 'n' and the desired stats, then put it in a 'manual' feature.
Is it ok if I take care of it?
Is it ok if it goes to mastodon-pasteur? or the core?

**Comment by stefanhahmann** [comment]
> Hello @stefanhahmann
> 
> Son in the team needs something that can compute statistics for the N nearest cells, whatever the stats is. I plan on making a plugin with a small UI that ask for 'n' and the desired stats, then put it in a 'manual' feature. Is it ok if I take care of it? Is it ok if it goes to mastodon-pasteur? or the core?

I would have had a slight preference for the core. But mastodon-pasteur is also fine. Nice to see that this progressing and thanks for linking the current state here, so that this can be followed also frome here.

**Comment by stefanhahmann** [comment]
cf.: https://github.com/mastodon-sc/mastodon-pasteur/pull/9

**Comment by stefanhahmann** [comment]
Solved via https://github.com/mastodon-sc/mastodon-pasteur/pull/9
