### ISSUE TITLE
Speed of cell division

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#63]
# UserStory

From a biological perspective, the `Speed of cell division` of a cell during its life cycle may be a good descriptor for the cell type or Cell state (e.g.: wound). Thus, it would be useful to have this information as a feature that may be computed from the cell lineage tree.

# Acceptance criteria
1. Available as Feature within the Feature Computer
1. Computes the Time between successiv cell divisions in tree

# Tasks
- [x] Implement Feature
- [x] Implement FeatureComputer
- [x] Write Unit test
- [x] Check cf.: https://github.com/mastodon-sc/mastodon/blob/master/src/main/java/org/mastodon/mamut/feature/branch/BranchDisplacementDurationFeature.java
- [x] ~NaN for "incomplete" BranchSpots, i.e. leaves and roots.~
- [x] Detect "incomplete" BranchSpots, i.e. leaves and roots via (new) BranchNSuccessors(Predecessors)Feature
- [x] Write documentation
