### ISSUE TITLE
Movement (speed and directionality) relative to neighbours 

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#65]
# UserStory

From a biological perspective, the `Movement (speed and directionality) relative to neighbours` of a cell during its life cycle may be a good descriptor for the cell type (e.g. epidermal vs. mesodermal vs. macrophage). Thus, it would be useful to have this information as a feature that may be computed from the cell lineage tree.

# Acceptance criteria
1. Available as Feature within the Feature Computer
1. Computes the Movement Speed and directionality relative to neighbours

# Tasks
- [x] Implement Feature
- [x] Implement FeatureComputer
- [x] Potential approach for relative speed (Spot level):
  - [x] Compute on spot level: n (e.g. 5) nearest neighbors (cf. nearest neighbor statistics feature).
  - [x] Compute displacement length on spot level (equals the speed, since the time frames are assumed constant)
  - [x] Compute average displacement of neighbors.
  - [x] Compute the difference of these two.
- [x] Compute the average of this over all spots of a BranchSpot to get the equivalent measure on BranchSpot level
- [x] Potential approach for relative direction (Spot level):
  - [x] Compute direction vectors (i.e. spot vs. previous spot) of all neighbours.
  - [x] Compute the sum of these and divide by number of neighbours
  - [x] Compute the difference between the spot vector and this sum and normalize the result.
- [x] Compute the average of this over all spots of a BranchSpot

- [x] Write Unit test
- [x] Write Documentation

# To be discussed

* Is anisotropy a problem for the approach? Can it be handled by setting and using scales of the axes?

# Notes

![grafik](https://github.com/mastodon-sc/mastodon-deep-lineage/assets/10515534/735a6e2f-836b-410b-9d56-523f9a834689)
