### ISSUE TITLE
Generation time of a BranchSpot

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#7]
# User Story

The generation time of a cell between to divisions be a possible descriptor of its fate already in early developmental stages. Thus, it would be good, if there was a feature computer that can compute the generation time of a cell.

# Acceptance criteria

1. Implemented as BrachSpot Feature
1. Result is stored per BranchSpot in the feature table

# Tasks

- [ ] Create a BranchSpot Feature "generation time"
- [ ] Compute the time between the timepoints when the cell has occurred and when it divides into 2 new cells.
- [ ] Store computed values in the feature table

**Comment by stefanhahmann** [comment]
@maarzt 
ah, maybe the difference is that the already existing duration feature refers to the difference of timepoints (and thus has no dimension), whereas the generation time of a branch spot would be expressed in some time units and would also indicate something different, if the duration time between the individual capturings of the images is not constant.

**Comment by tinevez** [comment]
The main issue is that BDV images do not store the time units. So we do not have access to time as we do in TrackMate :(
Tobias and co told us that they have a grant for BDV and imglib2 in which they will be able to make big changes at some point. We could propose the support of physical time units in BDV images, that would be the base for this in Mastodon.
Otherwise, we could look if physical units are supported in ZARR, and try to see if we can access them.

**Comment by stefanhahmann** [comment]
> The main issue is that BDV images do not store the time units. So we do not have access to time as we do in TrackMate :( Tobias and co told us that they have a grant for BDV and imglib2 in which they will be able to make big changes at some point. We could propose the support of physical time units in BDV images, that would be the base for this in Mastodon. Otherwise, we could look if physical units are supported in ZARR, and try to see if we can access them.

I understand. I was not aware that time units are not stored in BDV images.
Thanks, for the hint re Tobias. I have filed an issue for BDV here: https://github.com/bigdataviewer/bigdataviewer-core/issues/153
Re ZARR: I have had a look into the format. It seems to support custom attributes (https://zarr.readthedocs.io/en/stable/tutorial.html#user-attributes). They might be used to encode time units. However, it is not clear to me, where in the processing pipeline this info would need to be added (during the imaging? during the processing in BDV?). I would need more advice before, I could work on this.

As a conclusion, for the moment the necessary pre-conditions to work on this issue are not fulfilled. I will therefore close it.
