### ISSUE TITLE
Allow importing spots from segmented timelapse

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#83]
# User Story

A user would like to re-use his/her existing segmentation of time lapse images. The images are assumed to be in 3d and the segmentation may have been performed outside of Mastodon (e.g. using [StarDist3D](https://github.com/stardist/stardist)).

It would be good, if there was a possibility to read the segmented 3d images (aka label image) frame by frame and create a spot for each label in each frame. The user would then have a collection of spots in different frames, which he/she could link with each other by either using the Linking tools from [mastodon-tracking](https://github.com/mastodon-sc/mastodon-tracking) or from [elephant](https://elephant-track.github.io/#/v0.5/)

The possibility to import such existing datasets into mastodon may save the user a lot of time for tracking, if the image data has already been segmented outside of Mastodon.

# Acceptance criteria
1. Possibility to import spots from active Fiji image, if all dimensions match (i.e. x,y,z and t)
2. Possibility to import spots from selectable BDV channel
3. Possibility to set a sigma value which can be used to size the resulting ellipsoid
4. Image data is processed frame by frame
5. Each new pixel value results in a new label
6. The collection of pixel coordinates for each label is used to compute mean and covariance and from this the ellipsoids are derived.

# Tasks

- [x] Import command for active Fiji image
- [x] Check for matching dimensions
- [x] Import command for selectable BDV channel
- [x] Processing tools to create spots from image data
- [x] Unit tests
- [x] Documentation how to use the import
- [x] Documentation how to prepare data
- [x] Documentation how to use the linking after the import
