### ISSUE TITLE
Add similarity metric published in Guignard et al. to list of available similarity metrics

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-deep-lineage#97]
# User Story

In [Guignard et al. 2020](https://www.science.org/doi/10.1126/science.aar5663) a similarity metric, which is different from the currently available similarity metrics is implemented. In order to be able to reproduce the numbers published in this paper, users would like to be able to compute lineage classifications using this metric.

# Acceptance criteria
* A locally normalized cost function is added
* A new similarity metric is introduced

# Todos
* [x] Add Cost function
* [x] Add new metric to UI
* [x] Add unit tests

**Comment by stefanhahmann** [comment]
Interpretation of the constraints mentioned in the Zhang paper (section 3.1) and their relationship to the edit operations mentioned in the documentation of the ZhangEditDistance class and the readme of the Zhang edit distance.

![20240417_221326](https://github.com/mastodon-sc/mastodon-deep-lineage/assets/10515534/5dc6ce31-5012-4f90-825d-6dec8870d7bb)
